export type { FlaggingInitConfiguration, FlaggingTrackingInitConfiguration } from './domain/configuration'
export { DatadogDevtools } from './openfeature/devtools-provider'
export { createDatadogExposureLoggingHook } from './openfeature/exposures'
export { createDatadogEvaluationLoggingHook } from './openfeature/flagEvaluations'
export { DatadogProvider } from './openfeature/provider'
export { createDatadogRumTrackingHook } from './openfeature/rumIntegration'
export type { DatadogTrackingHook, DatadogTrackingHooks, DatadogTrackingHooksOptions } from './openfeature/tracking'
export { createDatadogTrackingHooks } from './openfeature/tracking'
