name: CI

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
  release:
    types: [created]

permissions:
  contents: read
  packages: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          # Uncomment for monorepo Yarn v1
          # cache-dependency-path: "**/yarn.lock"

      - name: Install dependencies
        run: yarn install --immutable && yarn allow-scripts

      - name: Lint
        run: yarn lint

      - name: Format
        run: yarn format:check

      - name: Validate package versions
        run: bash scripts/versions-validate.sh

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Test browser package installation
        run: yarn test:browser-install

      - name: Test node package installation (without OpenFeature)
        run: yarn test:node-install

      - name: Test node package installation (with OpenFeature)
        run: yarn test:node-install:with-of
